### ISSUE TITLE
Criar checklist da maturidade do Devops

### ISSUE THREAD

**Issue by matheusgomesf** [fga-eps-mds/2018.2-IndicaAi#196]
## Objetivo

Com o propósito de avaliar o quanto a equipe evolui em relação a Devops, deve-se criar um mecanismo de avaliação da maturidade do nosso devops, de forma que nós possamos acompanhá-lo ao longo da disciplina.

## Metas

- [ ] Criar uma planilha na pasta da equipe no Drive, a qual tenha os tópicos de maturidade e as sprints subsequentes, de forma que possamos avaliar em cada sprint.
  - [ ] Os tópicos que devem constar no checklist devem seguir a imagem abaixo.
- [ ] Gerar um gráfico em cima dos dados coletados.
- [ ] Criar uma página no Github Pages para exibição do gráfico.
  - [ ] O gráfico deve ser atualizado automaticamente no pages, a medida que é alterado no Drive.

![672feb7d-6f94-4f8f-8b3f-eda0799d1a0d](https://user-images.githubusercontent.com/17451476/46906914-14feb380-cee1-11e8-98a5-9a39169a16f4.jpeg)
